CREATE TABLE appel (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    id_finger INT NOT NULL,
    Date DATE NOT NULL,
    Présent BOOLEAN DEFAULT FALSE,
    Absent BOOLEAN DEFAULT FALSE
);
CREATE TABLE inscription (
    id INT AUTO_INCREMENT PRIMARY KEY,
    Nom VARCHAR(100) NOT NULL,
    Email VARCHAR(100) NOT NULL UNIQUE,
    Password VARCHAR(255) NOT NULL
);

